# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-yyuYw6vUv5_TJBrQR87We7jaLRH5Gco
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,3,6,9,12,15,18])
y=np.array([0,3,6,9,12,15,18])
mycolor=['red','green','purple','lime','aqua','yellow','blue']
size=[20,60,100,140,180,220,260]

plt.scatter(x,y,color=mycolor,s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['510','613','614'])
y=np.array([18,21,17])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['510','613','614'])
y=np.array([18,21,17])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([20,30,22,20])
mylabels=["Damas","Nexia 2","Gentra","Nexia 3"]

plt.pie(x,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([20,30,22,20])
mylabels=["Damas","Nexia 2","Gentra","Nexia 3"]
myexplode=[0,0.2,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([20,30,22,20])
mylabels=["Damas","Nexia 2","Gentra","Nexia 3"]

plt.pie(x,labels=mylabels)
plt.legend()
plt.show()